"""datu glabātuves struktūras izveide

Revision ID: d6bb71beac39
Revises: 
Create Date: 2026-09-30 14:36:41.345646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6bb71beac39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responsible_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOC', 'DOCX', 'ODT', 'RTF', 'TXT', 'XLS', 'XLSX', 'ODS', 'CSV', 'PPT', 'PPTX', 'ODP', 'XML', 'JSON', 'HTML', 'HTM', 'ZIP', 'RAR', 'SEVEN_Z', 'JPG', 'JPEG', 'PNG', 'GIF', 'SVG', 'WEBP', 'MP3', 'WAV', 'FLAC', 'MP4', 'AVI', 'MKV', 'MOV', name='filetype'), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='importancelevel'), nullable=False),
    sa.Column('category', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', 'CONFIDENTIAL', name='documentcategory'), nullable=False),
    sa.Column('is_active', sa.Enum('YES', 'NO', name='activestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
